### ISSUE TITLE
How to disable -Werror for clang using jrl-cmakemodules?

### ISSUE THREAD

**Issue by zongmianli** [jcarpent/pinocchio-ceres#1]
Hi Justin,

I tried to compile the latest commit (1fa77ac) but got the implicit conversion warning cast as an error [*] when compiling Google Test. It is shown that the flag `CXX_DISABLE_WERROR` (already set to `True`) is not taken into account by cmake.  The issue might be more related to jrl-cmakemodules, but I guess you are very familiar with it.

Thanks!
Zongmian

[*] Error message
> [  5%] Building CXX object tests/gtest/build/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
> cd /Users/zoli/Work/projects/pinocchio-ceres/build_debug/tests/gtest/build/googlemock/gtest && /Library/Developer/CommandLineTools/usr/bin/c++  -DMODEL_DIRECTORY=\"/Users/zoli/Work/projects/pinocchio-ceres/models\" -I/Users/zoli/Work/projects/pinocchio-ceres/build_debug -I/Users/zoli/Work/projects/pinocchio-ceres/build_debug/include -I/Users/zoli/Work/projects/pinocchio-ceres/include -I/Users/zoli/Work/projects/pinocchio-ceres/build_debug/tests/gtest/src/googletest/include -I/Users/zoli/Work/projects/pinocchio-ceres/build_debug/tests/gtest/src/googletest  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion    -Wall -Wshadow **-Werror** -DGTEST_HAS_PTHREAD=1 -fexceptions  -std=c++11 -o CMakeFiles/gtest.dir/src/gtest-all.cc.o -c /Users/zoli/Work/projects/pinocchio-ceres/build_debug/tests/gtest/src/googletest/src/gtest-all.cc

And I got the error
> In file included from /Users/zoli/Work/projects/pinocchio-ceres/build_debug/tests/gtest/src/googletest/src/gtest-all.cc:41:
> In file included from /Users/zoli/Work/projects/pinocchio-ceres/build_debug/tests/gtest/src/googletest/src/gtest.cc:122:
> /Users/zoli/Work/projects/pinocchio-ceres/build_debug/tests/gtest/src/googletest/src/gtest-internal-inl.h:323:32: error: 
>     **implicit conversion changes signedness: 'unsigned int' to 'const int' [-Werror,-Wsign-conversion]**
>     const int selected = begin + random->Generate(range_width);
>               ~~~~~~~~   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by zongmianli** [comment]
I did `MESSAGE(STATUS "CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}")` after `SETUP_PROJECT()` and got
> -- CMAKE_CXX_FLAGS:  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion 

which does not contain the -Werror flag (meaning that `CXX_DISABLE_WERROR` takes effect probably). I cannot figure out when the remaining 3 flags were appended by cmake
> ... -Wall -Wshadow **-Werror** ...

**Comment by zongmianli** [comment]
It turns out to be [a known Google test issue](https://github.com/google/googletest/pull/2137), which happens when compiling `gtest` using `clang` with the warning option `-Wsign-conversion` enabled.

A quick fix would be removing the flag `-Wconversion` from line 26, in [jrl-cmakemodules/compiler.cmake](https://github.com/jrl-umi3218/jrl-cmakemodules/blob/6ccc9f9b2a2ff510ae7754c515c72f8e38410447/compiler.cmake).

NB: simply removing `-Wconversion` would mute other useful warnings according to the `Clang 9 documentation`:
> **-Wconversion**
> Some of the diagnostics controlled by this flag are enabled by default.
> Also controls -Wbitfield-enum-conversion, -Wbool-conversion, -Wconstant-conversion, -Wenum-conversion, -Wfloat-conversion, -Wimplicit-float-conversion, -Wimplicit-int-conversion, -Wint-conversion, -Wliteral-conversion, -Wnon-literal-null-conversion, -Wnull-conversion, -Wobjc-literal-conversion, -Wshorten-64-to-32, **-Wsign-conversion**, -Wstring-conversion.

**Comment by jcarpent** [comment]
It seems that this is a very local mistake from the fast updates of the Gtest project. You might be able to provide an older commit version when using gtest normally. In this case, you won't have this trouble.

**Comment by zongmianli** [comment]
Thanks @jcarpent , I am closing the issue!

**Comment by ngie-eign** [comment]
These were issues that exist in the upstream version of googletest, but were masked because the warning was not being specified on the command line upstream. https://github.com/jrl-umi3218/jrl-cmakemodules/blob/6ccc9f9b2a2ff510ae7754c515c72f8e38410447/compiler.cmake defines strict compiler flags, which are used when building googletest, meaning that--because `-Werror` was tacked on--they will now error out.

Had you been compiling with gcc, you might have run into the same issue.

**Comment by ngie-eign** [comment]
The compiler issue is now being ignored on master. Please unpin the googletest version.
